/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Application main class
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {

  static Scanner keyScan;

  public static void main(String[] args) {

    keyScan = new Scanner(System.in);
    int no = getIntValue("번호:");
    String lectureName = getStringValue("이름:");
    String description = getStringValue("설명:");
    Date startDate = getDateValue("시작");
    Date endDate = getDateValue("종료");
    String totalHours = getStringValue("총수업:");

    int dayHours = getIntValue("일 수업:");


    System.out.printf("번호: %d\n", no);
    System.out.printf("수업명: 자바 프로젝트 실습 %s\n", lectureName);
    System.out.printf("설명: 자바 프로젝트를 통한 자바 언어 활용법 익히기 %s\n", description);
    System.out.printf("시작일: 2019-01-02 %s\n", startDate);
    System.out.printf("종료일: 2019-05-28 %s\n", endDate);
    System.out.printf("총수업시간: 1000 시간 %s\n", totalHours);
    System.out.printf("일수업시간: 8 시간 %s\n", dayHours);

  }

  private static String getStringValue(String message) {
    while(true) {
      try {
        System.out.println(message);
        return keyScan.nextLine();
      }catch (Exception e) {
        System.out.println("잘못 입력하셨습니다.");
      }
    }
  }

  private static int getIntValue(String message) {

    while (true) {
      try {
        System.out.println(message);
        return Integer.parseInt(keyScan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자가 아닌 값을 입력 했습니다. 다시 입력해주세요.");
      }
    }
  }
  
  private static Date getDateValue(String message) {

    while (true) {
      try {
        System.out.println(message);
        return Date.valueOf(keyScan.nextLine());
      } catch (IllegalArgumentException e) {
        System.out.println("2019-07-05 형식으로 입력하세요.");
      }
    }
  }
}
