/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Application main class
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.sql.Date;
import java.util.ArrayList;
import java.util.Scanner;

public class App {

  static Scanner keyScan;

  public static void main(String[] args) {

    keyScan = new Scanner(System.in);

    Lesson[] lessons = new Lesson[100];

    int i = 0;
    for (; i < lessons.length; i++) {
      Lesson lesson = new Lesson();

      // 사용자가 입력한 값을 Lesson인스턴스의 각 변수에 저장한다.
      lesson.no = getIntValue("번호?");
      lesson.title = getStringValue("수업명? ");
      lesson.contents = getStringValue("설명?");
      lesson.startDate = getDateValue("시작일?");
      lesson.endDate = getDateValue("종료일?");
      lesson.totalHours = getIntValue("총 쉅시간?");
      lesson.dayHours = getIntValue("일 쉅시간?");

      // 수업 데이터를 저장하고 있는 인스턴스의 주소를 레퍼런스 배열에 저장한다.
      lessons[i] = lesson;

      System.out.println("계속 입력 하시겠습니까?(Y or N) ");
      String response = keyScan.nextLine();

      if (response.equalsIgnoreCase("N"))
        break;
    }
    
    System.out.println();
    for (int i2 = 0; i2 <= i; i2++) {
      
      // 레퍼런스 배열에서 한 개의 인스턴스 주소를 꺼낸다.
      Lesson lesson = lessons[i2];
      
      // 그 인스턴스 주소로 찾아ㅏ서 인스턴스의 각 변수 값을 꺼내 출력한다.
      System.out.printf("%s, %s, %s ~ %s, %s, %s\n", lesson.no, lesson.title, lesson.startDate,
          lesson.endDate, lesson.totalHours, lesson.dayHours);
    }
  }
  
  private static String getStringValue(String message) {
    while (true) {
      try {
        System.out.println(message);
        return keyScan.nextLine();
      } catch (Exception e) {
        System.out.println("잘못 입력하셨습니다.");
      }
    }
  }

  private static int getIntValue(String message) {

    while (true) {
      try {
        System.out.println(message);
        return Integer.parseInt(keyScan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자가 아닌 값을 입력 했습니다. 다시 입력해주세요.");
      }
    }
  }

  private static Date getDateValue(String message) {

    while (true) {
      try {
        System.out.println(message);
        return Date.valueOf(keyScan.nextLine());
      } catch (IllegalArgumentException e) {
        System.out.println("2019-07-05 형식으로 입력하세요.");
      }
    }
  }
}
