/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.List;
import com.eomcs.lms.domain.Member;

public class ServerTest {

  static ObjectOutputStream out;
  static ObjectInputStream in;

  public static void main(String[] args) throws Exception {
    System.out.println("[Add&Drop class management Server Application Test!]");

    try (Socket socket = new Socket("192.168.43.153", 8888);
        ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream())) {
      ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
      // 서버와의 입출력을 위해 스트림 객체를 준비한다.
      System.out.println("Connect to server");

      ServerTest.in = in;
      ServerTest.out = out;
      // 서버에 전송할 객체를 준비한다.
      Member member = new Member();
      member.setNo(1);
      member.setName("Youlim Kim");
      member.setEmail("lima1016@gmail.com");
      member.setPhoto("kim.gif");
      member.setTel("1111-1111");

      add(member);

      member = new Member();
      member.setNo(2);
      member.setName("ss Kim");
      member.setEmail("eeef@gmail.com");
      member.setPhoto("23e.gif");
      member.setTel("fdw-1111");

      add(member);

      System.out.println("------------------------------");
      list();

      System.out.println("------------------------------");
      delete();

      System.out.println("------------------------------");
      quit();

    } catch (IOException e) {

      // 예외가 발생하면 일단 어디에서 예외가 발생했는지 확인하기 위해 호출 정보를 모두 출력한다.
      e.printStackTrace();
    }

    System.out.println("Disconnect");
  }

  private static void quit() throws Exception {
    // 서버가 처리할 수 없는 명령어 보내기
    out.writeUTF("quit");
    out.flush();
    System.out.println("quit 요청함 => ");

    if (!in.readUTF().equals("ok"))
      throw new Exception("서버 실행 오류");
    System.out.println("처리완료!");

  }

  private static void add(Member m) throws Exception {
    out.writeUTF("/member/add");
    out.writeObject(m);
    // 서버에 객체를 전송한다.
    out.flush();
    System.out.print("add 요청함 => ");

    // 서버에 보낸 데이터를 읽는다
    String response = in.readUTF();
    System.out.println(response);
  }

  private static void list() throws Exception {
    out.writeUTF("/member/list");
    out.flush();
    System.out.println("list 요청함 =>");

    String response = in.readUTF();
    System.out.println(response);

    @SuppressWarnings("unchecked")
    List<Member> list = (List<Member>) in.readObject();

    System.out.println("------------------------------");
    for (Member m : list) {
      System.out.println(m);
    }
  }

  private static void delete() throws Exception {
    // 서버가 처리할 수 없는 명령어 보내기
    out.writeUTF("/member/delete");
    out.flush();
    System.out.println("delete 요청함 => ");

    // fail일때
    String response = in.readUTF();
    System.out.println(response);

    // 서버가 보낸 데이터를 읽는다. (왜 fail인지 한번 더읽기)
    response = in.readUTF();
    System.out.println(response);

  }
}
